<a href="https://colab.research.google.com/github/juarezmauricio2305-droid/simple-nodejs-api/blob/main/Copia_Practica_2_1_de_El_metodo_groupby()_y_agg().ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data Analysis of Cell Phone Sales

In [ ]:
import pandas as pd
import numpy as np

# Create a dummy dataset for phone sales
data = {
    'Brand': ['Apple', 'Apple', 'Samsung', 'Samsung', 'Xiaomi', 'Xiaomi', 'Google', 'Google', 'OnePlus', 'OnePlus',
              'Apple', 'Samsung', 'Xiaomi', 'Google', 'OnePlus', 'Apple', 'Samsung', 'Xiaomi', 'Google', 'OnePlus'],
    'Model': ['iPhone 13', 'iPhone 13 Pro', 'Galaxy S22', 'Galaxy S22 Ultra', 'Redmi Note 11', 'Xiaomi 12 Pro', 'Pixel 6', 'Pixel 6 Pro', 'OnePlus 10 Pro', 'OnePlus Nord 2',
              'iPhone 14', 'Galaxy S23', 'Redmi Note 12', 'Pixel 7', 'OnePlus 11', 'iPhone SE', 'Galaxy A53', 'Redmi K50', 'Pixel 7a', 'OnePlus 10R'],
    'Sales_in_thousands': [500.5, 350.2, 400.1, 280.5, 600.3, 150.7, 180.9, 120.4, 90.6, 70.8,
                           550.0, 420.0, 650.0, 200.0, 110.0, 250.0, 300.0, 400.0, 160.0, 80.0],
    'Phone_type': ['Smartphone', 'Smartphone', 'Smartphone', 'Smartphone', 'Smartphone', 'Smartphone', 'Smartphone', 'Smartphone', 'Smartphone', 'Smartphone',
                   'Smartphone', 'Smartphone', 'Smartphone', 'Smartphone', 'Smartphone', 'Smartphone', 'Smartphone', 'Smartphone', 'Smartphone', 'Smartphone'],
    'Price_in_thousands': [0.999, 1.199, 0.899, 1.099, 0.249, 0.799, 0.599, 0.899, 0.699, 0.399,
                           1.099, 0.999, 0.299, 0.699, 0.799, 0.429, 0.449, 0.359, 0.499, 0.599],
    'Storage_GB': [128, 256, 128, 256, 64, 128, 128, 256, 128, 128,
                   128, 256, 64, 128, 256, 64, 128, 128, 128, 256],
    'Camera_MP': [12, 12, 50, 108, 50, 50, 50, 50, 48, 50,
                  12, 50, 50, 50, 50, 12, 64, 64, 64, 50],
    'Battery_mAh': [3240, 4352, 3700, 5000, 5000, 4600, 4614, 5003, 5000, 4500,
                    3279, 3900, 5000, 4410, 5000, 2018, 5000, 5500, 4410, 5000]
}

df_phones = pd.DataFrame(data)

# Introduce some NaN values to mimic the original dataset
df_phones.loc[2, 'Price_in_thousands'] = np.nan
df_phones.loc[5, 'Camera_MP'] = np.nan
df_phones.loc[10, 'Battery_mAh'] = np.nan

df_phones.to_csv('Phone_sales.csv', index=False)
print("Dummy 'Phone_sales.csv' created.")

Dummy 'Phone_sales.csv' created.

In [ ]:
import pandas as pd

In [ ]:
df_phones = pd.read_csv('Phone_sales.csv')

In [ ]:
df_phones

,Brand,Model,Sales_in_thousands,Phone_type,Price_in_thousands,Storage_GB,Camera_MP,Battery_mAh
0,Apple,iPhone 13,500.5,Smartphone,0.999,128,12.0,3240.0
1,Apple,iPhone 13 Pro,350.2,Smartphone,1.199,256,12.0,4352.0
2,Samsung,Galaxy S22,400.1,Smartphone,NaN,128,50.0,3700.0
3,Samsung,Galaxy S22 Ultra,280.5,Smartphone,1.099,256,108.0,5000.0
4,Xiaomi,Redmi Note 11,600.3,Smartphone,0.249,64,50.0,5000.0
5,Xiaomi,Xiaomi 12 Pro,150.7,Smartphone,0.799,128,NaN,4600.0
6,Google,Pixel 6,180.9,Smartphone,0.599,128,50.0,4614.0
7,Google,Pixel 6 Pro,120.4,Smartphone,0.899,256,50.0,5003.0
8,OnePlus,OnePlus 10 Pro,90.6,Smartphone,0.699,128,48.0,5000.0
9,OnePlus,OnePlus Nord 2,70.8,Smartphone,0.399,128,50.0,4500.0
10,Apple,iPhone 14,550.0,Smartphone,1.099,128,12.0,NaN
11,Samsung,Galaxy S23,420.0,Smartphone,0.999,256,50.0,3900.0
12,Xiaomi,Redmi Note 12,650.0,Smartphone,0.299,64,50.0,5000.0
13,Google,Pixel 7,200.0,Smartphone,0.699,128,50.0,4410.0
14,OnePlus,OnePlus 11,110.0,Smartphone,0.799,256,50.0,5000.0
15,Apple,iPhone SE,250.0,Smartphone,0.429,64,12.0,2018.0
16,Samsung,Galaxy A53,300.0,Smartphone,0.449,128,64.0,5000.0
17,Xiaomi,Redmi K50,400.0,Smartphone,0.359,128,64.0,5500.0
18,Google,Pixel 7a,160.0,Smartphone,0.499,128,64.0,4410.0
19,OnePlus,OnePlus 10R,80.0,Smartphone,0.599,256,50.0,5000.0

In [ ]:
df_phones = df_phones[['Brand', 'Sales_in_thousands',
                   'Phone_type', 'Price_in_thousands',
                   'Storage_GB', 'Camera_MP', 'Battery_mAh']]

In [ ]:
df_phones.nunique()

Brand                  5
Sales_in_thousands    20
Phone_type             1
Price_in_thousands    14
Storage_GB             3
Camera_MP              5
Battery_mAh           12
dtype: int64

# Metodo .agg()

In [ ]:
df_phones.agg('sum')

Brand                 AppleAppleSamsungSamsungXiaomiXiaomiGoogleGoog...
Sales_in_thousands                                               5865.0
Phone_type            SmartphoneSmartphoneSmartphoneSmartphoneSmartp...
Price_in_thousands                                               13.171
Storage_GB                                                         3136
Camera_MP                                                         896.0
Battery_mAh                                                     85247.0
dtype: object

In [ ]:
display(df_phones.agg('mean', numeric_only=True))

Sales_in_thousands     293.250000
Price_in_thousands       0.693211
Storage_GB             156.800000
Camera_MP               47.157895
Battery_mAh           4486.684211
dtype: float64

In [ ]:
display(df_phones.select_dtypes(include=np.number).agg(['sum', 'mean']))

,Sales_in_thousands,Price_in_thousands,Storage_GB,Camera_MP,Battery_mAh
sum,5865.00,13.171000,3136.0,896.000000,85247.000000
mean,293.25,0.693211,156.8,47.157895,4486.684211

In [ ]:
car_data = {
    'Manufacturer': ['Toyota', 'Honda', 'Ford', 'Chevrolet', 'Nissan', 'BMW', 'Mercedes-Benz', 'Audi', 'Tesla', 'Volvo',
                     'Toyota', 'Honda', 'Ford', 'Chevrolet', 'Nissan', 'BMW', 'Mercedes-Benz', 'Audi', 'Tesla', 'Volvo'],
    'Model': ['Camry', 'Civic', 'F-150', 'Silverado', 'Altima', '3 Series', 'C-Class', 'A4', 'Model 3', 'XC60',
              'Corolla', 'CR-V', 'Escape', 'Malibu', 'Rogue', 'X5', 'E-Class', 'Q5', 'Model S', 'S60'],
    'Sales_in_thousands': [350.0, 300.0, 800.0, 750.0, 250.0, 150.0, 180.0, 120.0, 200.0, 90.0,
                           320.0, 280.0, 500.0, 450.0, 220.0, 130.0, 160.0, 100.0, 190.0, 80.0],
    'Vehicle_type': ['Passenger', 'Passenger', 'Truck', 'Truck', 'Passenger', 'Passenger', 'Passenger', 'Passenger', 'Passenger', 'Passenger',
                     'Passenger', 'SUV', 'SUV', 'Passenger', 'SUV', 'SUV', 'Passenger', 'SUV', 'Passenger', 'Passenger'],
    'Price_in_thousands': [25.0, 22.0, 35.0, 38.0, 23.0, 40.0, 45.0, 38.0, 50.0, 35.0,
                           21.0, 28.0, 30.0, 26.0, 27.0, 55.0, 50.0, 42.0, 60.0, 40.0],
    'Engine_size': [2.5, 1.8, 3.5, 5.3, 2.5, 2.0, 3.0, 2.0, 0.0, 2.0,
                    1.8, 2.4, 1.5, 2.0, 2.5, 3.0, 3.0, 2.0, 0.0, 2.0],
    'Horsepower': [203, 158, 290, 355, 188, 181, 255, 201, 283, 250,
                   139, 190, 179, 160, 170, 335, 295, 248, 371, 246],
    'Fuel_capacity': [14.0, 12.4, 26.0, 24.0, 16.0, 15.6, 17.4, 15.3, 16.5, 15.9,
                      13.2, 14.0, 14.5, 15.8, 14.5, 17.2, 17.4, 18.5, 17.9, 14.5]
}

df_cars = pd.DataFrame(car_data)

# Introduce some NaN values
df_cars.loc[2, 'Price_in_thousands'] = np.nan
df_cars.loc[5, 'Horsepower'] = np.nan
df_cars.loc[10, 'Fuel_capacity'] = np.nan

df_cars.to_csv('Car_sales.csv', index=False)
print("Dummy 'Car_sales.csv' created.")

Dummy 'Car_sales.csv' created.

In [ ]:
display(df_phones.agg({'Sales_in_thousands':['sum', 'mean'],
             'Price_in_thousands':['sum', 'max']}))

      Sales_in_thousands  Price_in_thousands
sum              5865.00              13.171
mean              293.25                 NaN
max                  NaN               1.199

In [ ]:
df_phones

,Brand,Sales_in_thousands,Phone_type,Price_in_thousands,Storage_GB,Camera_MP,Battery_mAh
0,Apple,500.5,Smartphone,0.999,128,12.0,3240.0
1,Apple,350.2,Smartphone,1.199,256,12.0,4352.0
2,Samsung,400.1,Smartphone,NaN,128,50.0,3700.0
3,Samsung,280.5,Smartphone,1.099,256,108.0,5000.0
4,Xiaomi,600.3,Smartphone,0.249,64,50.0,5000.0
5,Xiaomi,150.7,Smartphone,0.799,128,NaN,4600.0
6,Google,180.9,Smartphone,0.599,128,50.0,4614.0
7,Google,120.4,Smartphone,0.899,256,50.0,5003.0
8,OnePlus,90.6,Smartphone,0.699,128,48.0,5000.0
9,OnePlus,70.8,Smartphone,0.399,128,50.0,4500.0
10,Apple,550.0,Smartphone,1.099,128,12.0,NaN
11,Samsung,420.0,Smartphone,0.999,256,50.0,3900.0
12,Xiaomi,650.0,Smartphone,0.299,64,50.0,5000.0
13,Google,200.0,Smartphone,0.699,128,50.0,4410.0
14,OnePlus,110.0,Smartphone,0.799,256,50.0,5000.0
15,Apple,250.0,Smartphone,0.429,64,12.0,2018.0
16,Samsung,300.0,Smartphone,0.449,128,64.0,5000.0
17,Xiaomi,400.0,Smartphone,0.359,128,64.0,5500.0
18,Google,160.0,Smartphone,0.499,128,64.0,4410.0
19,OnePlus,80.0,Smartphone,0.599,256,50.0,5000.0

In [ ]:
display(df_phones[['Sales_in_thousands', 'Price_in_thousands']].agg('sum', axis=1))

0     501.499
1     351.399
2     400.100
3     281.599
4     600.549
5     151.499
6     181.499
7     121.299
8      91.299
9      71.199
10    551.099
11    420.999
12    650.299
13    200.699
14    110.799
15    250.429
16    300.449
17    400.359
18    160.499
19     80.599
dtype: float64

In [ ]:
display(df_phones['Sales_in_thousands'] + df_phones['Price_in_thousands'])

0     501.499
1     351.399
2         NaN
3     281.599
4     600.549
5     151.499
6     181.499
7     121.299
8      91.299
9      71.199
10    551.099
11    420.999
12    650.299
13    200.699
14    110.799
15    250.429
16    300.449
17    400.359
18    160.499
19     80.599
dtype: float64

In [ ]:
display(df_phones.agg(total_sales=('Sales_in_thousands', 'sum'),
            max_price=('Price_in_thousands', 'max')))

             Sales_in_thousands  Price_in_thousands
total_sales              5865.0                 NaN
max_price                   NaN               1.199

# La estrategia Split-Apply-Combine

In [ ]:
# Let's categorize phones based on Price_in_thousands for demonstration
# split
high_end_filter = df_phones['Price_in_thousands'] >= 0.700
mid_range_filter = (df_phones['Price_in_thousands'] < 0.700) & (df_phones['Price_in_thousands'] >= 0.400)
low_end_filter = df_phones['Price_in_thousands'] < 0.400

In [ ]:
# apply
high_end_avg_sales = df_phones[high_end_filter]['Sales_in_thousands'].mean()
mid_range_avg_sales = df_phones[mid_range_filter]['Sales_in_thousands'].mean()
low_end_avg_sales = df_phones[low_end_filter]['Sales_in_thousands'].mean()

In [ ]:
# combine
pd.DataFrame({'Phone_Category':['High-End', 'Mid-Range', 'Low-End'],
              'Sales_in_thousands':[high_end_avg_sales, mid_range_avg_sales, low_end_avg_sales]}).set_index('Phone_Category')

                Sales_in_thousands
Phone_Category
High-End                310.287500
Mid-Range               180.214286
Low-End                 430.275000

# El metodo groupby()

In [ ]:
display(df_phones.groupby('Phone_type').mean(numeric_only=True))

,Sales_in_thousands,Price_in_thousands,Storage_GB,Camera_MP,Battery_mAh
Phone_type,,,,,
Smartphone,293.25,0.693211,156.8,47.157895,4486.684211

In [ ]:
grouped_by_brand = df_phones.groupby('Brand')
display(grouped_by_brand)

In [ ]:
grouped_by_brand

In [ ]:
grouped_by_brand.groups.keys()

dict_keys(['Apple', 'Google', 'OnePlus', 'Samsung', 'Xiaomi'])

In [ ]:
display(grouped_by_brand.get_group('Apple'))

,Brand,Sales_in_thousands,Phone_type,Price_in_thousands,Storage_GB,Camera_MP,Battery_mAh
0,Apple,500.5,Smartphone,0.999,128,12.0,3240.0
1,Apple,350.2,Smartphone,1.199,256,12.0,4352.0
10,Apple,550.0,Smartphone,1.099,128,12.0,NaN
15,Apple,250.0,Smartphone,0.429,64,12.0,2018.0

In [ ]:
df_phones.groupby('Brand').mean(numeric_only=True)

,Sales_in_thousands,Price_in_thousands,Storage_GB,Camera_MP,Battery_mAh
Brand,,,,,
Apple,412.675,0.9315,144.0,12.000000,3203.333333
Google,165.325,0.6740,160.0,53.500000,4609.250000
OnePlus,87.850,0.6240,192.0,49.500000,4875.000000
Samsung,350.150,0.8490,192.0,68.000000,4400.000000
Xiaomi,450.250,0.4265,96.0,54.666667,5025.000000

In [ ]:
df_phones.groupby('Brand').sum(numeric_only=True)

,Sales_in_thousands,Price_in_thousands,Storage_GB,Camera_MP,Battery_mAh
Brand,,,,,
Apple,1650.7,3.726,576,48.0,9610.0
Google,661.3,2.696,640,214.0,18437.0
OnePlus,351.4,2.496,768,198.0,19500.0
Samsung,1400.6,2.547,768,272.0,17600.0
Xiaomi,1801.0,1.706,384,164.0,20100.0

In [ ]:
display(df_phones.groupby('Phone_type').count())

,Brand,Sales_in_thousands,Price_in_thousands,Storage_GB,Camera_MP,Battery_mAh
Phone_type,,,,,,
Smartphone,20,20,19,20,19,19

In [ ]:
display(df_phones.isnull().sum())

Brand                 0
Sales_in_thousands    0
Phone_type            0
Price_in_thousands    1
Storage_GB            0
Camera_MP             1
Battery_mAh           1
dtype: int64

In [ ]:
display(df_phones.groupby('Camera_MP', dropna=False).count())

,Brand,Sales_in_thousands,Phone_type,Price_in_thousands,Storage_GB,Battery_mAh
Camera_MP,,,,,,
12.0,4,4,4,4,4,3
48.0,1,1,1,1,1,1
50.0,10,10,10,9,10,10
64.0,3,3,3,3,3,3
108.0,1,1,1,1,1,1
NaN,1,1,1,1,1,1

# Groupby() y agg()

In [ ]:
display(df_phones.groupby('Phone_type').agg({
    'Sales_in_thousands': ['min', 'max'],
    'Price_in_thousands': ['min', 'max'],
    'Storage_GB': ['min', 'max'],
    'Camera_MP': ['min', 'max'],
    'Battery_mAh': ['min', 'max']
}))

           Sales_in_thousands        Price_in_thousands        Storage_GB  \
                          min    max                min    max        min
Phone_type
Smartphone               70.8  650.0              0.249  1.199         64

                Camera_MP        Battery_mAh
            max       min    max         min     max
Phone_type
Smartphone  256      12.0  108.0      2018.0  5500.0

In [ ]:
display(df_phones.groupby('Brand').agg(min_storage_gb=('Storage_GB', 'min'),
                                     max_camera_mp=('Camera_MP', 'max')))

         min_storage_gb  max_camera_mp
Brand
Apple                64           12.0
Google              128           64.0
OnePlus             128           50.0
Samsung             128          108.0
Xiaomi               64           64.0

In [ ]:
df_phones.columns

Index(['Brand', 'Sales_in_thousands', 'Phone_type', 'Price_in_thousands',
       'Storage_GB', 'Camera_MP', 'Battery_mAh'],
      dtype='object')

In [ ]:
display(df_phones.groupby('Brand').agg(sum_sales=('Sales_in_thousands', 'sum'),
                                    mean_price=('Price_in_thousands', 'mean')))

         sum_sales  mean_price
Brand
Apple       1650.7      0.9315
Google       661.3      0.6740
OnePlus      351.4      0.6240
Samsung     1400.6      0.8490
Xiaomi      1801.0      0.4265

In [ ]:
display(df_phones.groupby('Brand').sum(numeric_only=True)['Sales_in_thousands'].head())

Brand
Apple      1650.7
Google      661.3
OnePlus     351.4
Samsung    1400.6
Xiaomi     1801.0
Name: Sales_in_thousands, dtype: float64

In [ ]:
display(df_phones.groupby('Brand').mean(numeric_only=True)['Price_in_thousands'].head())

Brand
Apple      0.9315
Google     0.6740
OnePlus    0.6240
Samsung    0.8490
Xiaomi     0.4265
Name: Price_in_thousands, dtype: float64

# Lambdac

In [ ]:
display(df_phones.groupby('Brand').sum(numeric_only=True).head())

,Sales_in_thousands,Price_in_thousands,Storage_GB,Camera_MP,Battery_mAh
Brand,,,,,
Apple,1650.7,3.726,576,48.0,9610.0
Google,661.3,2.696,640,214.0,18437.0
OnePlus,351.4,2.496,768,198.0,19500.0
Samsung,1400.6,2.547,768,272.0,17600.0
Xiaomi,1801.0,1.706,384,164.0,20100.0

In [ ]:
display(df_phones.groupby('Brand').sum(numeric_only=True).apply(lambda x:x*1000)[['Sales_in_thousands','Price_in_thousands']])

         Sales_in_thousands  Price_in_thousands
Brand
Apple             1650700.0              3726.0
Google             661300.0              2696.0
OnePlus            351400.0              2496.0
Samsung           1400600.0              2547.0
Xiaomi            1801000.0              1706.0

In [ ]:
# subtract mean values from each group
display(df_phones.groupby('Brand').apply(lambda x:x - x.mean(numeric_only=True)))

/tmp/ipykernel_9431/1461761259.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  display(df_phones.groupby('Brand').apply(lambda x:x - x.mean(numeric_only=True)))

            Battery_mAh Brand  Camera_MP Phone_type  Price_in_thousands  \
Brand
Apple   0     36.666667   NaN   0.000000        NaN              0.0675
        1   1148.666667   NaN   0.000000        NaN              0.2675
        10          NaN   NaN   0.000000        NaN              0.1675
        15 -1185.333333   NaN   0.000000        NaN             -0.5025
Google  6      4.750000   NaN  -3.500000        NaN             -0.0750
        7    393.750000   NaN  -3.500000        NaN              0.2250
        13  -199.250000   NaN  -3.500000        NaN              0.0250
        18  -199.250000   NaN  10.500000        NaN             -0.1750
OnePlus 8    125.000000   NaN  -1.500000        NaN              0.0750
        9   -375.000000   NaN   0.500000        NaN             -0.2250
        14   125.000000   NaN   0.500000        NaN              0.1750
        19   125.000000   NaN   0.500000        NaN             -0.0250
Samsung 2   -700.000000   NaN -18.000000        NaN                 NaN
        3    600.000000   NaN  40.000000        NaN              0.2500
        11  -500.000000   NaN -18.000000        NaN              0.1500
        16   600.000000   NaN  -4.000000        NaN             -0.4000
Xiaomi  4    -25.000000   NaN  -4.666667        NaN             -0.1775
        5   -425.000000   NaN        NaN        NaN              0.3725
        12   -25.000000   NaN  -4.666667        NaN             -0.1275
        17   475.000000   NaN   9.333333        NaN             -0.0675

            Sales_in_thousands  Storage_GB
Brand
Apple   0               87.825       -16.0
        1              -62.475       112.0
        10             137.325       -16.0
        15            -162.675       -80.0
Google  6               15.575       -32.0
        7              -44.925        96.0
        13              34.675       -32.0
        18              -5.325       -32.0
OnePlus 8                2.750       -64.0
        9              -17.050       -64.0
        14              22.150        64.0
        19              -7.850        64.0
Samsung 2               49.950       -64.0
        3              -69.650        64.0
        11              69.850        64.0
        16             -50.150       -64.0
Xiaomi  4              150.050       -32.0
        5             -299.550        32.0
        12             199.750       -32.0
        17             -50.250        32.0

In [ ]:
display(df_phones)

,Brand,Sales_in_thousands,Phone_type,Price_in_thousands,Storage_GB,Camera_MP,Battery_mAh
0,Apple,500.5,Smartphone,0.999,128,12.0,3240.0
1,Apple,350.2,Smartphone,1.199,256,12.0,4352.0
2,Samsung,400.1,Smartphone,NaN,128,50.0,3700.0
3,Samsung,280.5,Smartphone,1.099,256,108.0,5000.0
4,Xiaomi,600.3,Smartphone,0.249,64,50.0,5000.0
5,Xiaomi,150.7,Smartphone,0.799,128,NaN,4600.0
6,Google,180.9,Smartphone,0.599,128,50.0,4614.0
7,Google,120.4,Smartphone,0.899,256,50.0,5003.0
8,OnePlus,90.6,Smartphone,0.699,128,48.0,5000.0
9,OnePlus,70.8,Smartphone,0.399,128,50.0,4500.0
10,Apple,550.0,Smartphone,1.099,128,12.0,NaN
11,Samsung,420.0,Smartphone,0.999,256,50.0,3900.0
12,Xiaomi,650.0,Smartphone,0.299,64,50.0,5000.0
13,Google,200.0,Smartphone,0.699,128,50.0,4410.0
14,OnePlus,110.0,Smartphone,0.799,256,50.0,5000.0
15,Apple,250.0,Smartphone,0.429,64,12.0,2018.0
16,Samsung,300.0,Smartphone,0.449,128,64.0,5000.0
17,Xiaomi,400.0,Smartphone,0.359,128,64.0,5500.0
18,Google,160.0,Smartphone,0.499,128,64.0,4410.0
19,OnePlus,80.0,Smartphone,0.599,256,50.0,5000.0

In [ ]:
display(df_phones.groupby('Brand').mean(numeric_only=True))

,Sales_in_thousands,Price_in_thousands,Storage_GB,Camera_MP,Battery_mAh
Brand,,,,,
Apple,412.675,0.9315,144.0,12.000000,3203.333333
Google,165.325,0.6740,160.0,53.500000,4609.250000
OnePlus,87.850,0.6240,192.0,49.500000,4875.000000
Samsung,350.150,0.8490,192.0,68.000000,4400.000000
Xiaomi,450.250,0.4265,96.0,54.666667,5025.000000

# El metodo filter()

In [ ]:
display(df_phones.mean(numeric_only=True))

Sales_in_thousands     293.250000
Price_in_thousands       0.693211
Storage_GB             156.800000
Camera_MP               47.157895
Battery_mAh           4486.684211
dtype: float64

In [ ]:
def filter_func_phones(x):
    return x['Sales_in_thousands'].sum() > 100

df_filter_phones = df_phones.groupby(['Brand']).filter(filter_func_phones)
display(df_filter_phones)

,Brand,Sales_in_thousands,Phone_type,Price_in_thousands,Storage_GB,Camera_MP,Battery_mAh
0,Apple,500.5,Smartphone,0.999,128,12.0,3240.0
1,Apple,350.2,Smartphone,1.199,256,12.0,4352.0
2,Samsung,400.1,Smartphone,NaN,128,50.0,3700.0
3,Samsung,280.5,Smartphone,1.099,256,108.0,5000.0
4,Xiaomi,600.3,Smartphone,0.249,64,50.0,5000.0
5,Xiaomi,150.7,Smartphone,0.799,128,NaN,4600.0
6,Google,180.9,Smartphone,0.599,128,50.0,4614.0
7,Google,120.4,Smartphone,0.899,256,50.0,5003.0
8,OnePlus,90.6,Smartphone,0.699,128,48.0,5000.0
9,OnePlus,70.8,Smartphone,0.399,128,50.0,4500.0
10,Apple,550.0,Smartphone,1.099,128,12.0,NaN
11,Samsung,420.0,Smartphone,0.999,256,50.0,3900.0
12,Xiaomi,650.0,Smartphone,0.299,64,50.0,5000.0
13,Google,200.0,Smartphone,0.699,128,50.0,4410.0
14,OnePlus,110.0,Smartphone,0.799,256,50.0,5000.0
15,Apple,250.0,Smartphone,0.429,64,12.0,2018.0
16,Samsung,300.0,Smartphone,0.449,128,64.0,5000.0
17,Xiaomi,400.0,Smartphone,0.359,128,64.0,5500.0
18,Google,160.0,Smartphone,0.499,128,64.0,4410.0
19,OnePlus,80.0,Smartphone,0.599,256,50.0,5000.0

In [ ]:
display(df_phones.groupby(['Brand']).sum(numeric_only=True)['Sales_in_thousands'].sort_values().head(3))

Brand
OnePlus     351.4
Google      661.3
Samsung    1400.6
Name: Sales_in_thousands, dtype: float64

In [ ]:
display(df_phones[df_phones['Brand'].isin(['OnePlus', 'Google'])].shape)

(8, 7)

In [ ]:
print(df_phones.shape)
print(df_filter_phones.shape)

(20, 7)
(20, 7)

In [ ]:
import pandas as pd

In [ ]:
df_cars = pd.read_csv('Car_sales.csv')
display(df_cars)

,Manufacturer,Model,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Toyota,Camry,350.0,Passenger,25.0,2.5,203.0,14.0
1,Honda,Civic,300.0,Passenger,22.0,1.8,158.0,12.4
2,Ford,F-150,800.0,Truck,NaN,3.5,290.0,26.0
3,Chevrolet,Silverado,750.0,Truck,38.0,5.3,355.0,24.0
4,Nissan,Altima,250.0,Passenger,23.0,2.5,188.0,16.0
5,BMW,3 Series,150.0,Passenger,40.0,2.0,NaN,15.6
6,Mercedes-Benz,C-Class,180.0,Passenger,45.0,3.0,255.0,17.4
7,Audi,A4,120.0,Passenger,38.0,2.0,201.0,15.3
8,Tesla,Model 3,200.0,Passenger,50.0,0.0,283.0,16.5
9,Volvo,XC60,90.0,Passenger,35.0,2.0,250.0,15.9
10,Toyota,Corolla,320.0,Passenger,21.0,1.8,139.0,NaN
11,Honda,CR-V,280.0,SUV,28.0,2.4,190.0,14.0
12,Ford,Escape,500.0,SUV,30.0,1.5,179.0,14.5
13,Chevrolet,Malibu,450.0,Passenger,26.0,2.0,160.0,15.8
14,Nissan,Rogue,220.0,SUV,27.0,2.5,170.0,14.5
15,BMW,X5,130.0,SUV,55.0,3.0,335.0,17.2
16,Mercedes-Benz,E-Class,160.0,Passenger,50.0,3.0,295.0,17.4
17,Audi,Q5,100.0,SUV,42.0,2.0,248.0,18.5
18,Tesla,Model S,190.0,Passenger,60.0,0.0,371.0,17.9
19,Volvo,S60,80.0,Passenger,40.0,2.0,246.0,14.5

In [ ]:
display(df_cars)

,Manufacturer,Model,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Toyota,Camry,350.0,Passenger,25.0,2.5,203.0,14.0
1,Honda,Civic,300.0,Passenger,22.0,1.8,158.0,12.4
2,Ford,F-150,800.0,Truck,NaN,3.5,290.0,26.0
3,Chevrolet,Silverado,750.0,Truck,38.0,5.3,355.0,24.0
4,Nissan,Altima,250.0,Passenger,23.0,2.5,188.0,16.0
5,BMW,3 Series,150.0,Passenger,40.0,2.0,NaN,15.6
6,Mercedes-Benz,C-Class,180.0,Passenger,45.0,3.0,255.0,17.4
7,Audi,A4,120.0,Passenger,38.0,2.0,201.0,15.3
8,Tesla,Model 3,200.0,Passenger,50.0,0.0,283.0,16.5
9,Volvo,XC60,90.0,Passenger,35.0,2.0,250.0,15.9
10,Toyota,Corolla,320.0,Passenger,21.0,1.8,139.0,NaN
11,Honda,CR-V,280.0,SUV,28.0,2.4,190.0,14.0
12,Ford,Escape,500.0,SUV,30.0,1.5,179.0,14.5
13,Chevrolet,Malibu,450.0,Passenger,26.0,2.0,160.0,15.8
14,Nissan,Rogue,220.0,SUV,27.0,2.5,170.0,14.5
15,BMW,X5,130.0,SUV,55.0,3.0,335.0,17.2
16,Mercedes-Benz,E-Class,160.0,Passenger,50.0,3.0,295.0,17.4
17,Audi,Q5,100.0,SUV,42.0,2.0,248.0,18.5
18,Tesla,Model S,190.0,Passenger,60.0,0.0,371.0,17.9
19,Volvo,S60,80.0,Passenger,40.0,2.0,246.0,14.5

In [ ]:
df_cars = df_cars[['Manufacturer', 'Sales_in_thousands',
                   'Vehicle_type', 'Price_in_thousands',
                   'Engine_size', 'Horsepower', 'Fuel_capacity']]
display(df_cars)

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Toyota,350.0,Passenger,25.0,2.5,203.0,14.0
1,Honda,300.0,Passenger,22.0,1.8,158.0,12.4
2,Ford,800.0,Truck,NaN,3.5,290.0,26.0
3,Chevrolet,750.0,Truck,38.0,5.3,355.0,24.0
4,Nissan,250.0,Passenger,23.0,2.5,188.0,16.0
5,BMW,150.0,Passenger,40.0,2.0,NaN,15.6
6,Mercedes-Benz,180.0,Passenger,45.0,3.0,255.0,17.4
7,Audi,120.0,Passenger,38.0,2.0,201.0,15.3
8,Tesla,200.0,Passenger,50.0,0.0,283.0,16.5
9,Volvo,90.0,Passenger,35.0,2.0,250.0,15.9
10,Toyota,320.0,Passenger,21.0,1.8,139.0,NaN
11,Honda,280.0,SUV,28.0,2.4,190.0,14.0
12,Ford,500.0,SUV,30.0,1.5,179.0,14.5
13,Chevrolet,450.0,Passenger,26.0,2.0,160.0,15.8
14,Nissan,220.0,SUV,27.0,2.5,170.0,14.5
15,BMW,130.0,SUV,55.0,3.0,335.0,17.2
16,Mercedes-Benz,160.0,Passenger,50.0,3.0,295.0,17.4
17,Audi,100.0,SUV,42.0,2.0,248.0,18.5
18,Tesla,190.0,Passenger,60.0,0.0,371.0,17.9
19,Volvo,80.0,Passenger,40.0,2.0,246.0,14.5

In [ ]:
display(df_cars.nunique())

Manufacturer          10
Sales_in_thousands    20
Vehicle_type           3
Price_in_thousands    16
Engine_size            9
Horsepower            19
Fuel_capacity         15
dtype: int64

# Metodo .agg()

In [ ]:
display(df_cars.agg('sum'))

Manufacturer          ToyotaHondaFordChevroletNissanBMWMercedes-Benz...
Sales_in_thousands                                               5620.0
Vehicle_type          PassengerPassengerTruckTruckPassengerPassenger...
Price_in_thousands                                                695.0
Engine_size                                                        44.8
Horsepower                                                       4516.0
Fuel_capacity                                                     317.4
dtype: object

In [ ]:
display(df_cars.agg('mean', numeric_only=True))

Sales_in_thousands    281.000000
Price_in_thousands     36.578947
Engine_size             2.240000
Horsepower            237.684211
Fuel_capacity          16.705263
dtype: float64

In [ ]:
display(df_cars.select_dtypes(include=np.number).agg(['sum', 'mean']))

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
sum,5620.0,695.000000,44.80,4516.000000,317.400000
mean,281.0,36.578947,2.24,237.684211,16.705263

In [ ]:
display(df_cars.agg({'Sales_in_thousands':['sum', 'mean'],
             'Price_in_thousands':['sum', 'max']}))

      Sales_in_thousands  Price_in_thousands
sum               5620.0               695.0
mean               281.0                 NaN
max                  NaN                60.0

In [ ]:
display(df_cars)

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Toyota,350.0,Passenger,25.0,2.5,203.0,14.0
1,Honda,300.0,Passenger,22.0,1.8,158.0,12.4
2,Ford,800.0,Truck,NaN,3.5,290.0,26.0
3,Chevrolet,750.0,Truck,38.0,5.3,355.0,24.0
4,Nissan,250.0,Passenger,23.0,2.5,188.0,16.0
5,BMW,150.0,Passenger,40.0,2.0,NaN,15.6
6,Mercedes-Benz,180.0,Passenger,45.0,3.0,255.0,17.4
7,Audi,120.0,Passenger,38.0,2.0,201.0,15.3
8,Tesla,200.0,Passenger,50.0,0.0,283.0,16.5
9,Volvo,90.0,Passenger,35.0,2.0,250.0,15.9
10,Toyota,320.0,Passenger,21.0,1.8,139.0,NaN
11,Honda,280.0,SUV,28.0,2.4,190.0,14.0
12,Ford,500.0,SUV,30.0,1.5,179.0,14.5
13,Chevrolet,450.0,Passenger,26.0,2.0,160.0,15.8
14,Nissan,220.0,SUV,27.0,2.5,170.0,14.5
15,BMW,130.0,SUV,55.0,3.0,335.0,17.2
16,Mercedes-Benz,160.0,Passenger,50.0,3.0,295.0,17.4
17,Audi,100.0,SUV,42.0,2.0,248.0,18.5
18,Tesla,190.0,Passenger,60.0,0.0,371.0,17.9
19,Volvo,80.0,Passenger,40.0,2.0,246.0,14.5

In [ ]:
display(df_cars[['Sales_in_thousands', 'Price_in_thousands']].agg('sum', axis=1))

0     375.0
1     322.0
2     800.0
3     788.0
4     273.0
5     190.0
6     225.0
7     158.0
8     250.0
9     125.0
10    341.0
11    308.0
12    530.0
13    476.0
14    247.0
15    185.0
16    210.0
17    142.0
18    250.0
19    120.0
dtype: float64

In [ ]:
display(df_cars['Sales_in_thousands'] + df_cars['Price_in_thousands'])

0     375.0
1     322.0
2       NaN
3     788.0
4     273.0
5     190.0
6     225.0
7     158.0
8     250.0
9     125.0
10    341.0
11    308.0
12    530.0
13    476.0
14    247.0
15    185.0
16    210.0
17    142.0
18    250.0
19    120.0
dtype: float64

In [ ]:
display(df_cars.agg(x=('Sales_in_thousands', 'sum'),
            y=('Price_in_thousands', 'sum')))

   Sales_in_thousands  Price_in_thousands
x              5620.0                 NaN
y                 NaN               695.0

# La estrategia Split-Apply-Combine

In [ ]:
# split
# car_filter = df_cars['Vehicle_type']=='Car'
# Corrected filter to use 'Truck' as 'Car' is not present in the dataframe
car_filter = df_cars['Vehicle_type']=='Truck'
passenger_filter = df_cars['Vehicle_type']=='Passenger'

In [ ]:
# apply
car_average = df_cars[car_filter]['Sales_in_thousands'].mean()
passenger_average = df_cars[passenger_filter]['Sales_in_thousands'].mean()

In [ ]:
# combine
display(pd.DataFrame({'Vehicle_Type':['Truck', 'Passenger'],
              'Sales_in_thousands':[car_average, passenger_average]}).set_index('Vehicle_Type'))

              Sales_in_thousands
Vehicle_Type
Passenger                    NaN
Passenger             218.461538

# El metodo groupby()

In [ ]:
display(df_cars.groupby('Vehicle_type').mean(numeric_only=True))

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Vehicle_type,,,,,
Passenger,218.461538,36.538462,1.892308,229.083333,15.725
SUV,246.000000,36.400000,2.280000,224.400000,15.740
Truck,775.000000,38.000000,4.400000,322.500000,25.000

In [ ]:
objeto_groupby = df_cars.groupby('Manufacturer')
display(objeto_groupby)

In [ ]:
display(objeto_groupby)

In [ ]:
display(objeto_groupby.groups.keys())

dict_keys(['Audi', 'BMW', 'Chevrolet', 'Ford', 'Honda', 'Mercedes-Benz', 'Nissan', 'Tesla', 'Toyota', 'Volvo'])

In [ ]:
display(objeto_groupby.get_group('Ford'))

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
2,Ford,800.0,Truck,NaN,3.5,290.0,26.0
12,Ford,500.0,SUV,30.0,1.5,179.0,14.5

In [ ]:
display(df_cars.groupby('Manufacturer').mean(numeric_only=True))

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Manufacturer,,,,,
Audi,110.0,40.0,2.00,224.5,16.90
BMW,140.0,47.5,2.50,335.0,16.40
Chevrolet,600.0,32.0,3.65,257.5,19.90
Ford,650.0,30.0,2.50,234.5,20.25
Honda,290.0,25.0,2.10,174.0,13.20
Mercedes-Benz,170.0,47.5,3.00,275.0,17.40
Nissan,235.0,25.0,2.50,179.0,15.25
Tesla,195.0,55.0,0.00,327.0,17.20
Toyota,335.0,23.0,2.15,171.0,14.00
Volvo,85.0,37.5,2.00,248.0,15.20

In [ ]:
display(df_cars.groupby('Manufacturer').sum(numeric_only=True))

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Manufacturer,,,,,
Audi,220.0,80.0,4.0,449.0,33.8
BMW,280.0,95.0,5.0,335.0,32.8
Chevrolet,1200.0,64.0,7.3,515.0,39.8
Ford,1300.0,30.0,5.0,469.0,40.5
Honda,580.0,50.0,4.2,348.0,26.4
Mercedes-Benz,340.0,95.0,6.0,550.0,34.8
Nissan,470.0,50.0,5.0,358.0,30.5
Tesla,390.0,110.0,0.0,654.0,34.4
Toyota,670.0,46.0,4.3,342.0,14.0
Volvo,170.0,75.0,4.0,496.0,30.4

In [ ]:
display(df_cars.groupby('Vehicle_type').count())

,Manufacturer,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Vehicle_type,,,,,,
Passenger,13,13,13,13,12,12
SUV,5,5,5,5,5,5
Truck,2,2,1,2,2,2

In [ ]:
display(df_cars.isnull().sum())

Manufacturer          0
Sales_in_thousands    0
Vehicle_type          0
Price_in_thousands    1
Engine_size           0
Horsepower            1
Fuel_capacity         1
dtype: int64

In [ ]:
display(df_cars.groupby('Engine_size', dropna=False).count())

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Horsepower,Fuel_capacity
Engine_size,,,,,,
0.0,2,2,2,2,2,2
1.5,1,1,1,1,1,1
1.8,2,2,2,2,2,1
2.0,6,6,6,6,5,6
2.4,1,1,1,1,1,1
2.5,3,3,3,3,3,3
3.0,3,3,3,3,3,3
3.5,1,1,1,0,1,1
5.3,1,1,1,1,1,1

# Groupby() y agg()

In [ ]:
display(df_cars.groupby('Vehicle_type')[df_cars.select_dtypes(include=np.number).columns].agg(['min', 'max']))

             Sales_in_thousands        Price_in_thousands       Engine_size  \
                            min    max                min   max         min
Vehicle_type
Passenger                  80.0  450.0               21.0  60.0         0.0
SUV                       100.0  500.0               27.0  55.0         1.5
Truck                     750.0  800.0               38.0  38.0         3.5

                  Horsepower        Fuel_capacity
              max        min    max           min   max
Vehicle_type
Passenger     3.0      139.0  371.0          12.4  17.9
SUV           3.0      170.0  335.0          14.0  18.5
Truck         5.3      290.0  355.0          24.0  26.0

In [ ]:
display(df_cars.groupby('Vehicle_type').agg(min_engine_size=('Engine_size', 'min'),
                                     max_horsepower=('Horsepower', 'max')))

              min_engine_size  max_horsepower
Vehicle_type
Passenger                 0.0           371.0
SUV                       1.5           335.0
Truck                     3.5           355.0

In [ ]:
display(df_cars.columns)

Index(['Manufacturer', 'Sales_in_thousands', 'Vehicle_type',
       'Price_in_thousands', 'Engine_size', 'Horsepower', 'Fuel_capacity'],
      dtype='object')

In [ ]:
display(df_cars.groupby('Manufacturer').agg(sum_sales=('Sales_in_thousands', 'sum'),
                                    mean_price=('Price_in_thousands', 'mean')))

               sum_sales  mean_price
Manufacturer
Audi               220.0        40.0
BMW                280.0        47.5
Chevrolet         1200.0        32.0
Ford              1300.0        30.0
Honda              580.0        25.0
Mercedes-Benz      340.0        47.5
Nissan             470.0        25.0
Tesla              390.0        55.0
Toyota             670.0        23.0
Volvo              170.0        37.5

In [ ]:
display(df_cars.groupby('Manufacturer').sum(numeric_only=True)['Sales_in_thousands'].head())

Manufacturer
Audi          220.0
BMW           280.0
Chevrolet    1200.0
Ford         1300.0
Honda         580.0
Name: Sales_in_thousands, dtype: float64

In [ ]:
display(df_cars.groupby('Manufacturer').mean(numeric_only=True)['Price_in_thousands'].head())

Manufacturer
Audi         40.0
BMW          47.5
Chevrolet    32.0
Ford         30.0
Honda        25.0
Name: Price_in_thousands, dtype: float64

# Lambda

In [ ]:
display(df_cars.groupby('Manufacturer').sum(numeric_only=True).head())

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Manufacturer,,,,,
Audi,220.0,80.0,4.0,449.0,33.8
BMW,280.0,95.0,5.0,335.0,32.8
Chevrolet,1200.0,64.0,7.3,515.0,39.8
Ford,1300.0,30.0,5.0,469.0,40.5
Honda,580.0,50.0,4.2,348.0,26.4

In [ ]:
display(df_cars.groupby('Manufacturer').sum(numeric_only=True).apply(lambda x:x*1000)[['Sales_in_thousands','Price_in_thousands']])

               Sales_in_thousands  Price_in_thousands
Manufacturer
Audi                     220000.0             80000.0
BMW                      280000.0             95000.0
Chevrolet               1200000.0             64000.0
Ford                    1300000.0             30000.0
Honda                    580000.0             50000.0
Mercedes-Benz            340000.0             95000.0
Nissan                   470000.0             50000.0
Tesla                    390000.0            110000.0
Toyota                   670000.0             46000.0
Volvo                    170000.0             75000.0

In [ ]:
# restar valores de la media a cada grupo
display(df_cars.groupby('Manufacturer').apply(lambda x:x-x.mean(numeric_only=True), include_groups=False))

                  Engine_size  Fuel_capacity  Horsepower  Price_in_thousands  \
Manufacturer
Audi          7          0.00          -1.60       -23.5                -2.0
              17         0.00           1.60        23.5                 2.0
BMW           5         -0.50          -0.80         NaN                -7.5
              15         0.50           0.80         0.0                 7.5
Chevrolet     3          1.65           4.10        97.5                 6.0
              13        -1.65          -4.10       -97.5                -6.0
Ford          2          1.00           5.75        55.5                 NaN
              12        -1.00          -5.75       -55.5                 0.0
Honda         1         -0.30          -0.80       -16.0                -3.0
              11         0.30           0.80        16.0                 3.0
Mercedes-Benz 6          0.00           0.00       -20.0                -2.5
              16         0.00           0.00        20.0                 2.5
Nissan        4          0.00           0.75         9.0                -2.0
              14         0.00          -0.75        -9.0                 2.0
Tesla         8          0.00          -0.70       -44.0                -5.0
              18         0.00           0.70        44.0                 5.0
Toyota        0          0.35           0.00        32.0                 2.0
              10        -0.35            NaN       -32.0                -2.0
Volvo         9          0.00           0.70         2.0                -2.5
              19         0.00          -0.70        -2.0                 2.5

                  Sales_in_thousands Vehicle_type
Manufacturer
Audi          7                 10.0          NaN
              17               -10.0          NaN
BMW           5                 10.0          NaN
              15               -10.0          NaN
Chevrolet     3                150.0          NaN
              13              -150.0          NaN
Ford          2                150.0          NaN
              12              -150.0          NaN
Honda         1                 10.0          NaN
              11               -10.0          NaN
Mercedes-Benz 6                 10.0          NaN
              16               -10.0          NaN
Nissan        4                 15.0          NaN
              14               -15.0          NaN
Tesla         8                  5.0          NaN
              18                -5.0          NaN
Toyota        0                 15.0          NaN
              10               -15.0          NaN
Volvo         9                  5.0          NaN
              19                -5.0          NaN

In [ ]:
display(df_cars)

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Toyota,350.0,Passenger,25.0,2.5,203.0,14.0
1,Honda,300.0,Passenger,22.0,1.8,158.0,12.4
2,Ford,800.0,Truck,NaN,3.5,290.0,26.0
3,Chevrolet,750.0,Truck,38.0,5.3,355.0,24.0
4,Nissan,250.0,Passenger,23.0,2.5,188.0,16.0
5,BMW,150.0,Passenger,40.0,2.0,NaN,15.6
6,Mercedes-Benz,180.0,Passenger,45.0,3.0,255.0,17.4
7,Audi,120.0,Passenger,38.0,2.0,201.0,15.3
8,Tesla,200.0,Passenger,50.0,0.0,283.0,16.5
9,Volvo,90.0,Passenger,35.0,2.0,250.0,15.9
10,Toyota,320.0,Passenger,21.0,1.8,139.0,NaN
11,Honda,280.0,SUV,28.0,2.4,190.0,14.0
12,Ford,500.0,SUV,30.0,1.5,179.0,14.5
13,Chevrolet,450.0,Passenger,26.0,2.0,160.0,15.8
14,Nissan,220.0,SUV,27.0,2.5,170.0,14.5
15,BMW,130.0,SUV,55.0,3.0,335.0,17.2
16,Mercedes-Benz,160.0,Passenger,50.0,3.0,295.0,17.4
17,Audi,100.0,SUV,42.0,2.0,248.0,18.5
18,Tesla,190.0,Passenger,60.0,0.0,371.0,17.9
19,Volvo,80.0,Passenger,40.0,2.0,246.0,14.5

In [ ]:
display(df_cars.groupby('Manufacturer').mean(numeric_only=True))

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Manufacturer,,,,,
Audi,110.0,40.0,2.00,224.5,16.90
BMW,140.0,47.5,2.50,335.0,16.40
Chevrolet,600.0,32.0,3.65,257.5,19.90
Ford,650.0,30.0,2.50,234.5,20.25
Honda,290.0,25.0,2.10,174.0,13.20
Mercedes-Benz,170.0,47.5,3.00,275.0,17.40
Nissan,235.0,25.0,2.50,179.0,15.25
Tesla,195.0,55.0,0.00,327.0,17.20
Toyota,335.0,23.0,2.15,171.0,14.00
Volvo,85.0,37.5,2.00,248.0,15.20

# El metodo filter()

In [ ]:
display(df_cars.mean(numeric_only=True))

Sales_in_thousands    281.000000
Price_in_thousands     36.578947
Engine_size             2.240000
Horsepower            237.684211
Fuel_capacity          16.705263
dtype: float64

In [ ]:
def filter_func(x):
    return x['Sales_in_thousands'].sum() > 52

df_filter = df_cars.groupby(['Manufacturer']).filter(filter_func)
display(df_filter)

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Toyota,350.0,Passenger,25.0,2.5,203.0,14.0
1,Honda,300.0,Passenger,22.0,1.8,158.0,12.4
2,Ford,800.0,Truck,NaN,3.5,290.0,26.0
3,Chevrolet,750.0,Truck,38.0,5.3,355.0,24.0
4,Nissan,250.0,Passenger,23.0,2.5,188.0,16.0
5,BMW,150.0,Passenger,40.0,2.0,NaN,15.6
6,Mercedes-Benz,180.0,Passenger,45.0,3.0,255.0,17.4
7,Audi,120.0,Passenger,38.0,2.0,201.0,15.3
8,Tesla,200.0,Passenger,50.0,0.0,283.0,16.5
9,Volvo,90.0,Passenger,35.0,2.0,250.0,15.9
10,Toyota,320.0,Passenger,21.0,1.8,139.0,NaN
11,Honda,280.0,SUV,28.0,2.4,190.0,14.0
12,Ford,500.0,SUV,30.0,1.5,179.0,14.5
13,Chevrolet,450.0,Passenger,26.0,2.0,160.0,15.8
14,Nissan,220.0,SUV,27.0,2.5,170.0,14.5
15,BMW,130.0,SUV,55.0,3.0,335.0,17.2
16,Mercedes-Benz,160.0,Passenger,50.0,3.0,295.0,17.4
17,Audi,100.0,SUV,42.0,2.0,248.0,18.5
18,Tesla,190.0,Passenger,60.0,0.0,371.0,17.9
19,Volvo,80.0,Passenger,40.0,2.0,246.0,14.5

In [ ]:
display(df_cars.groupby(['Manufacturer']).sum(numeric_only=True)['Sales_in_thousands'].sort_values().head(7))

Manufacturer
Volvo            170.0
Audi             220.0
BMW              280.0
Mercedes-Benz    340.0
Tesla            390.0
Nissan           470.0
Honda            580.0
Name: Sales_in_thousands, dtype: float64

In [ ]:
display(df_cars[df_cars['Manufacturer'].isin(['BMW','Audi','Infiniti','Saab','Jaguar','Porsche'])].shape)

(4, 7)

In [ ]:
print(df_cars.shape)
print(df_filter.shape)

(20, 7)
(20, 7)